version: "3.8"

services:

  web:
      build: .
      command: python -u run.py
      ports:
        - "5000:5000"
      volumes:
        - .:/workit
      depends_on:
        - db

  db:
      image: mongo:latest
