CATEGORIES = {
    "Frontend": {
        "frontend",
        "front",
        "typescript",
        "javascript",
        "js",
        "vue",
        "react",
        "angular",
        "html",
        "css",
        "sass",
        "node",
        "acf",
        "wordpress",
        "cms",
        "ember",
        "express",
        "jquery",
        "redux",
        "vue.js",
        "node.js",
        "react.js",
    },
    "Backend": {
        "backend",
        "back",
        "python",
        "java",
        "rails",
        "ruby",
        "php",
        "symfony",
        "django",
        "pyramid",
        "flask",
        "asp.net",
        "mvc",
        "apache",
        "entity",
        "golang",
        "graphql",
        "hadoop",
        "laravel",
        "drupal",
        ".net",
        "c#",
        "go",
    },
    "Fullstack": {"fullstack", "full", "stack"},
    "Mobile": {
        "mobile",
        "kotlin",
        "swift",
        "xamarin",
        "objectivec",
        "android",
        "ios",
        "flutter",
    },
    "Data Science": {
        "data",
        "database",
        "db",
        "sql",
        "etl",
        "ai",
        "ml",
        "artificial",
        "nlp",
        "machine",
        "learning",
        "keras",
        "pytorch",
        "natural",
        "automl",
        "matlab",
    },
    "C/C++": {"c", "c++"},
    "Networks": {
        "sip",
        "tcp",
        "ccna",
        "ccnp",
        "cisco",
        "networking",
        "haproxy",
        "kerberos",
        "network",
        "sieci",
        "sieciowy",
    },
    "DevOps": {"devops", "ansible", "ops"},
    "Testing": {"test", "qa", "junit", "tester", "quality", "pentester"},
    "Cloud": {
        "cloud", "aws", "azure", "amazon web services",
        "heroku", "cloudops"
    },
    "Embedded": {"embedded", "firmware"},
    "Hardware": {"hardware"},
    "GameDev": {"game", "unity", "unreal", "gameplay"},
    "Analytics": {
        "bi", "analiza", "analityk", "analysis", "analyst", "analytics"
    },
    "Administration": {"admin", "administrator"},
    "RPA": {"rpa", "robotic", "anywhere automation", "uipath", "blueprism"},
    "SAP": {"sap", "abap", "hana"},
    "Security": {"security", "cryptography", "cybersecurity"},
    "Design": {"designer", "ui", "ux", "design", "adobe", "photoshop"},
    "Ecommerce": {"sales", "ecommerce", "salesforce", "magento"},
    "Support": {"helpdesk", "support", "service", "supporter"},
    "Management": {
        "scrum",
        "manager",
        "management",
        "cto",
        "leader",
        "lead",
        "product",
        "head",
    },
    "HR": {"recruitment", "recruit", "recruiter", "lms"},
    "Functional Programming": {"haskell", "f#", "scala"},
    "Automotive": {"autosar", "automotive"},
}

CURRENCIES = {
    "PLN": {"pln", "zł", "złoty"},
    "EUR": {"eur", "euro", "€"},
    "USD": {"usd", "dollar", "dolar", "$"},
}

LOCATIONS = {
    "Warszawa",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
    "Katowice",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Kielce",
    "Rzeszów",
    "Gliwice",
    "Zabrze",
    "Olsztyn",
    "Bielsko-Biała",
    "Bytom",
    "Zielona Góra",
    "Rybnik",
    "Ruda Śląska",
    "Opole",
    "Tychy",
    "Gorzów Wielkopolski",
    "Dąbrowa Górnicza",
    "Elbląg",
    "Płock",
    "Wałbrzych",
    "Włocławek",
    "Tarnów",
    "Chorzów",
    "Koszalin",
    "Kalisz",
    "Legnica",
    "Grudziądz",
    "Jaworzno",
    "Słupsk",
    "Jastrzębie-Zdrój",
    "Nowy Sącz",
    "Jelenia Góra",
    "Siedlce",
    "Mysłowice",
    "Konin",
    "Piotrków Trybunalski",
    "Piła",
    "Inowrocław",
    "Lubin",
    "Ostrów Wielkopolski",
    "Suwałki",
    "Ostrowiec Świętokrzyski",
    "Gniezno",
    "Stargard",
    "Głogów",
    "Siemianowice Śląskie",
    "Pabianice",
    "Zamość",
    "Leszno",
    "Łomża",
    "Chełm",
    "Tomaszów Mazowiecki",
    "Żory",
    "Ełk",
    "Stalowa Wola",
    "Pruszków",
    "Przemyśl",
    "Kędzierzyn-Koźle",
    "Tarnowskie Góry",
    "Mielec",
    "Tczew",
    "Bełchatów",
    "Biała Podlaska",
    "Świdnica",
    "Będzin",
    "Zgierz",
    "Piekary Śląskie",
    "Racibórz",
    "Legionowo",
    "Ostrołęka",
    "Świętochłowice",
    "Wejherowo",
    "Zawiercie",
    "Starachowice",
    "Rumia",
    "Skierniewice",
    "Wodzisław Śląski",
    "Starogard Gdański",
    "Puławy",
    "Piaseczno",
    "Tarnobrzeg",
    "Krosno",
    "Kołobrzeg",
    "Radomsko",
    "Dębica",
    "Skarżysko-Kamienna",
    "Otwock",
    "Kutno",
    "Ciechanów",
    "Nysa",
    "Sieradz",
    "Zduńska Wola",
    "Świnoujście",
    "Mińsk Mazowiecki",
    "Mikołów",
    "Szczecinek",
    "Żyrardów",
    "Chojnice",
    "Świdnik",
    "Bolesławiec",
    "Nowa Sól",
    "Malbork",
    "Kwidzyn",
    "Oświęcim",
    "Knurów",
    "Sanok",
    "Jarosław",
    "Żary",
    "Oleśnica",
    "Wołomin",
    "Chrzanów",
    "Sochaczew",
    "Sopot",
    "Ząbki",
    "Brzeg",
    "Czechowice-Dziedzice",
    "Olkusz",
    "Lębork",
    "Jasło",
    "Cieszyn",
    "Kraśnik",
    "Dzierżoniów",
    "Nowy Targ",
    "Marki",
    "Iława",
    "Ostróda",
    "Oława",
    "Police",
    "Myszków",
    "Czeladź",
    "Luboń",
    "Żywiec",
    "Mława",
    "Grodzisk Mazowiecki",
    "Pruszcz Gdański",
    "Swarzędz",
    "Zgorzelec",
    "Września",
    "Augustów",
    "Łuków",
    "Bielawa",
    "Bochnia",
    "Śrem",
    "Giżycko",
    "Krotoszyn",
    "Brodnica",
    "Nowy Dwór Mazowiecki",
    "Łowicz",
    "Czerwionka-Leszczyny",
    "Gorlice",
    "Kętrzyn",
    "Zakopane",
    "Turek",
    "Kłodzko",
    "Wyszków",
    "Biłgoraj",
    "Jarocin",
    "Żagań",
    "Świecie",
    "Pszczyna",
    "Wągrowiec",
    "Reda",
    "Bielsk Podlaski",
    "Wałcz",
    "Skawina",
    "Białogard",
    "Lubliniec",
    "Kościan",
    "Kościerzyna",
    "Sandomierz",
    "Bartoszyce",
    "Kluczbork",
    "Kobyłka",
    "Szczytno",
    "Wieliczka",
    "Środa Wielkopolska",
    "Jawor",
    "Świebodzice",
    "Piastów",
    "Wieluń",
    "Ostrów Mazowiecka",
    "Polkowice",
    "Goleniów",
    "Łaziska Górne",
    "Nowa Ruda",
    "Płońsk",
    "Zambrów",
    # Zagranica
    "Budapest",
    # Zdalnie
    "Remote"
}

from workit.websites.BullDog import BullDogJobs  # noqa E402
from workit.websites.JustJoin import JustJoinJobs  # noqa E402
from workit.websites.NoFluff import NoFluffJobs  # noqa E402
from workit.websites.JobsForGeek import JobsForGeek  # noqa E402
from workit.websites.Pracuj import PracujJobs  # noqa E402

WEBSITES = [
    JustJoinJobs(),
    NoFluffJobs(),
    BullDogJobs(),
    JobsForGeek(),
    PracujJobs()
]
